### ISSUE TITLE
Install error: 'compact-prediciton-tree@*' is not in the npm registry.

### ISSUE THREAD

**Issue by homanp** [ashubham/CPT#1]
Hey there, 

Getting an install error when running `npm i compact-prediciton-tree`:

Install error: 'compact-prediciton-tree@*' is not in the npm registry.

**Comment by homanp** [comment]
Any ideas on this @ashubham?! Any help would be appreciated.

**Comment by ashubham** [comment]
@homanp Sorry for the delayed response. There was a typo in the package name.

Please try `npm i compact-prediction-tree` instead. I corrected on the readme as well.
